# Generated by Django 5.0.7 on 2024-07-10 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_exchanges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchange',
            name='item_offered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_exchanges', to='items.item'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='item_requested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_in_exchanges', to='items.item'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_exchanges', to=settings.AUTH_USER_MODEL),
        ),
    ]
