# Generated by Django 5.0.7 on 2024-08-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
    ]
