# Generated by Django 5.0.7 on 2024-08-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20240808_1922'),
        ('notifications', '0003_auto_20240808_1924'),
    ]

    operations = [
    ]
